# Generated by Django 3.0.5 on 2022-08-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dailypricelst',
            fields=[
                ('proserialnum', models.IntegerField(primary_key=True, serialize=False)),
                ('probrand', models.CharField(max_length=50)),
                ('prodate', models.DateField()),
                ('prounit', models.CharField(max_length=30)),
                ('proprice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
