# Generated by Django 4.1 on 2022-09-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=11)),
                ('msg', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
