# Generated by Django 3.0.5 on 2022-08-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPanter',
            fields=[
                ('lbrNum', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='carpenterimages/')),
                ('Name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=20)),
                
                ('description', models.CharField(max_length=90)),
            ],
        ),
    ]
