# Generated by Django 4.1 on 2022-09-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laborservices', '0003_carpanter_lbrcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpanter',
            name='lbrcontact',
        ),
    ]
