# Generated by Django 4.1 on 2022-09-19 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='public_houseownerdetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=60)),
                ('owner_name', models.CharField(max_length=50)),
                ('phoneNumber', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='publicreadymadehouseimg')),
                ('house_price', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('date_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='public_readyhouseimggallery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='publicreadymadehouseimg')),
                ('fk', models.ForeignKey(default=b'N', on_delete=django.db.models.deletion.CASCADE, to='publichome.public_houseownerdetail')),
            ],
        ),
    ]
