# Generated by Django 4.1 on 2022-09-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publichome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_readyhouseimggallery',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
