# Generated by Django 4.1 on 2022-09-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publichome', '0002_alter_public_readyhouseimggallery_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_readyhouseimggallery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
