# Generated by Django 4.1 on 2022-09-19 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publichome', '0004_alter_public_readyhouseimggallery_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_readyhouseimggallery',
            name='fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publichome.public_houseownerdetail'),
        ),
    ]
